---
title: "HW5"
author: "Carlos Juarez"
date: "11/15/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{bash}
cd ..
cd data/
ls -a
```
Choice 2: Recreate the graph shown below. It shows monthly homicides in Baltimore, with a reference added for the date of the arrest of Freddie Gray and color used to show colder months (November through April) versus warmer months (May through October). There is a smooth line added to help show seasonal and long-term trends in this data.
```{r}
#load data and packages

library(readr)
library(tidyverse)
library(lubridate)
library(ggthemes)

hom <- read_csv("../data/homicide-data.csv")
```


```{r}
#make plot, choice 2

hom %>% 
  filter(city == "Baltimore") %>%
  mutate(reported_date = ymd(reported_date), 
         year = year(reported_date), 
         month = month(reported_date), 
         year_month = paste(year, month), 
         year_month = ym(year_month)) %>%
  group_by(year_month) %>%
  count() %>%
  ungroup() %>%
  mutate(cold = ifelse(month(year_month) %in% c(11, 12, 1, 2, 3, 4), "Winter", "Summer")) %>%
  ggplot() +
  geom_col(aes(x = year_month, y = n, fill = cold)) +
  scale_fill_manual(values = c("gray71", "skyblue1")) +
  geom_smooth(aes(x = year_month, y = n), span = .09, se = FALSE) +
  theme_dark() +
  ylab("Monthly homicides") +
  xlab("Date") +
  ggtitle("Homicides in Baltimore, MD") +
  geom_vline(xintercept = ymd("2015-04-01"), color = "red", linetype = "dashed", size = 1.1) +
  geom_text(aes(x = ymd("2014-06-01"), y = 40, label = "Arrest of\n Freddie Grey        "), 
            color = "grey88") + #had to "eyeball" the position, but I imagine theres an automatic way to do this 
  theme(legend.position = "bottom", legend.title =  element_blank(), aspect.ratio = .2)

```

